"""
Carve a "large trash" subset out of the converted datasets.

Rationale: the three source datasets annotate objects at wildly different
scales — median box area is 0.07% of the image for UAVVaste, 0.35% for TACO,
and 4.4% for SIH. Training on all of it at once asks one model to solve two
different problems. This script isolates the easier half (bags, piles, dumped
furniture) so the detector can be proven to work there first.

Filtering is done at the BOX level, not the image level: boxes smaller than
--min-area are dropped from the label file, and an image is kept only if at
least one box survives. Small litter still visible in a kept image therefore
becomes unlabelled background — that is intentional. It teaches the model to
ignore small objects, which is what a large-trash detector should do.

Usage:
    python scripts/make_large_subset.py --min-area 0.01 --symlink

Creates:
    datasets/large/
    ├── images/{train,val,val_taco,val_uavvaste,val_sih}/
    └── labels/{train,val,val_taco,val_uavvaste,val_sih}/

The per-source val splits keep the ST-04 cross-dataset benchmark available at
this scale. Configs are written to configs/large*.yaml.
"""
import argparse
import shutil
from pathlib import Path


DATASETS = ["taco", "uavvaste", "sih"]
IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp"}


def filter_label(lbl_path: Path, min_area: float) -> list[str]:
    """Return the label lines whose box area is at least min_area.

    Areas are relative (YOLO w/h are normalized), so this is a fraction of the
    image, not pixels — which is the comparable measure across datasets whose
    source resolutions differ by 10x.
    """
    kept = []
    for line in lbl_path.read_text().splitlines():
        parts = line.split()
        if len(parts) < 5:
            continue
        if float(parts[3]) * float(parts[4]) >= min_area:
            kept.append(line)
    return kept


def build_split(base: Path, out: Path, split: str, dest: str,
                min_area: float, symlink: bool) -> dict[str, tuple[int, int]]:
    """Filter one split of every dataset into out/{images,labels}/dest.

    Returns {dataset: (images_kept, boxes_kept)}.
    """
    (out / "images" / dest).mkdir(parents=True, exist_ok=True)
    (out / "labels" / dest).mkdir(parents=True, exist_ok=True)

    stats = {}
    for ds in DATASETS:
        imgs_dir = base / ds / "images" / split
        lbls_dir = base / ds / "labels" / split
        if not imgs_dir.exists():
            stats[ds] = (0, 0)
            continue

        n_imgs = n_boxes = 0
        for img in sorted(imgs_dir.iterdir()):
            if img.suffix.lower() not in IMG_EXTS:
                continue
            lbl = lbls_dir / (img.stem + ".txt")
            if not lbl.exists():
                continue

            kept = filter_label(lbl, min_area)
            if not kept:
                continue

            dst_img = out / "images" / dest / f"{ds}_{img.name}"
            dst_lbl = out / "labels" / dest / f"{ds}_{img.stem}.txt"

            if not dst_img.exists():
                if symlink:
                    dst_img.symlink_to(img.resolve())
                else:
                    shutil.copy2(img, dst_img)
            # Labels are rewritten rather than copied — they differ from source.
            dst_lbl.write_text("\n".join(kept) + "\n")

            n_imgs += 1
            n_boxes += len(kept)

        stats[ds] = (n_imgs, n_boxes)
    return stats


def write_config(path: Path, dataset_dir: Path, val_dest: str, note: str):
    path.write_text(
        f"# TrashTrack — large-trash subset\n"
        f"# {note}\n"
        f"# Generated by scripts/make_large_subset.py — do not edit by hand.\n"
        f"\n"
        f"path: {dataset_dir}\n"
        f"train: images/train\n"
        f"val: images/{val_dest}\n"
        f"\n"
        f"nc: 1\n"
        f"names:\n"
        f"  0: litter\n"
    )


def main():
    parser = argparse.ArgumentParser(description="Build the large-trash subset")
    parser.add_argument("--datasets-dir", default="datasets")
    parser.add_argument("--output", default="datasets/large")
    parser.add_argument("--min-area", type=float, default=0.01,
                        help="Minimum box area as a fraction of image area "
                             "(default 0.01 = 1%%)")
    parser.add_argument("--symlink", action="store_true",
                        help="Symlink images instead of copying (saves ~10 GB)")
    args = parser.parse_args()

    base = Path(args.datasets_dir)
    out = Path(args.output)

    print(f"Minimum box area: {args.min_area * 100:.2f}% of image\n")

    print("TRAIN")
    train_stats = build_split(base, out, "train", "train", args.min_area, args.symlink)
    for ds, (n_i, n_b) in train_stats.items():
        print(f"  {ds:10s} {n_i:5d} images  {n_b:5d} boxes")

    print("\nVAL (combined, used for the training run's own metrics)")
    val_stats = build_split(base, out, "val", "val", args.min_area, args.symlink)
    for ds, (n_i, n_b) in val_stats.items():
        print(f"  {ds:10s} {n_i:5d} images  {n_b:5d} boxes")

    # Per-source val splits so the ST-04 cross-dataset benchmark still works.
    print("\nVAL (per-source, for ST-04)")
    for ds in DATASETS:
        single = build_split(base, out, "val", f"val_{ds}", args.min_area, args.symlink)
        # build_split writes every dataset into the dest; prune the others.
        for other in DATASETS:
            if other == ds:
                continue
            for d in ("images", "labels"):
                for f in (out / d / f"val_{ds}").glob(f"{other}_*"):
                    f.unlink()
        n_i, n_b = single[ds]
        print(f"  {ds:10s} {n_i:5d} images  {n_b:5d} boxes")

    cfg_dir = Path("configs")
    write_config(cfg_dir / "large.yaml", out, "val",
                 f"Boxes >= {args.min_area * 100:.2f}% of image area, all sources.")
    for ds in DATASETS:
        write_config(cfg_dir / f"large_{ds}.yaml", out, f"val_{ds}",
                     f"Boxes >= {args.min_area * 100:.2f}% of image area, {ds} val only.")

    total_train = sum(n for n, _ in train_stats.values())
    total_val = sum(n for n, _ in val_stats.values())
    print(f"\nTotal: {total_train} train / {total_val} val images")
    print(f"Dataset at: {out}")
    print(f"Configs:    configs/large.yaml, configs/large_{{{','.join(DATASETS)}}}.yaml")


if __name__ == "__main__":
    main()
